// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tributacao_Singular.Infra.Contexto;

#nullable disable

namespace Tributacao_Singular.Infra.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    [Migration("20220123184805_Mudanca Mapeamento")]
    partial class MudancaMapeamento
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Tributacao_Singular.Negocio.Modelos.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cofins")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ICMS")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("IPI")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Tributacao_Singular.Negocio.Modelos.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("cnpj")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Tributacao_Singular.Negocio.Modelos.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tabela")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Tributacao_Singular.Negocio.Modelos.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EAN")
                        .IsRequired()
                        .HasColumnType("varchar(13)");

                    b.Property<string>("NCM")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Tributacao_Singular.Negocio.Modelos.Produto", b =>
                {
                    b.HasOne("Tributacao_Singular.Negocio.Modelos.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .IsRequired();

                    b.HasOne("Tributacao_Singular.Negocio.Modelos.Cliente", "Cliente")
                        .WithMany("Produtos")
                        .HasForeignKey("ClienteId")
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Tributacao_Singular.Negocio.Modelos.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Tributacao_Singular.Negocio.Modelos.Cliente", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
